version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://postgres:postgres@db:5432/music-db?schema=public
      - NODE_ENV: production
      - JWT_SECRET: "a1f1cdb20fcbefc0e83baa28131eb124490b8220f739bab3e9ec5fa45a6a6e20d105bf46319de525765dc944b4dfd1a0b5d9aac9abd2b425c741958f0d5062bf"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: music-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
